### ISSUE TITLE
failed to use VSCode WSL

### ISSUE THREAD

**Issue by 117503445** [LGUG2Z/nixos-wsl-starter#1]
After I uncommented the vscode-remote-workaround block, it still doesn't work with the vscode wsl.

## VSCode WSL Extension Log

![image](https://github.com/LGUG2Z/nixos-wsl-starter/assets/21152034/3a762f84-04f2-4aac-8e65-1d9f9f2ad025)

`Starting server: /home/nixos/.vscode-server/bin/d037ac076cee195194f93ce6fe2bdfe2969cc82d/bin/code-server --host=127.0.0.1 --port=0 --connection-token=1057041771-2303584977-2822485713-267384198 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --disable-telemetry --telemetry-level=off`

## WSL Version

```plaintext
WSL 版本： 2.0.4.0
内核版本： 5.15.123.1-1
WSLg 版本： 1.0.58
MSRDC 版本： 1.2.4485
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25880.1000-230602-1350.main
Windows 版本： 10.0.22621.2506
```

( `版本` means `version`, `内核` means `kernel`)

**Comment by LGUG2Z** [comment]
Can you share the systemd output for the job that patches the `node` binary?

```
❯ systemctl status --user vscode-remote-workaround
○ vscode-remote-workaround.service
     Loaded: loaded (/etc/systemd/user/vscode-remote-workaround.service; static)
     Active: inactive (dead) since Thu 2023-11-02 15:23:16 UTC; 3 days ago
   Duration: 9ms
TriggeredBy: ● vscode-remote-workaround.path
    Process: 1525 ExecStart=/nix/store/rmc015jlx3immqzmmvii5a9fi4cavc4f-unit-script-vscode-remote-workaround-start/bin/vscode-remote-workaround-start (code=exited, status=0/SUCCESS)
   Main PID: 1525 (code=exited, status=0/SUCCESS)

Nov 02 15:23:16 nixsl systemd[819]: Started vscode-remote-workaround.service.
Nov 02 15:23:16 nixsl vscode-remote-workaround-start[1525]: Fixing vscode-server in /home/user/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc...
```

**Comment by 117503445** [comment]
```sh
❯ systemctl status --user vscode-remote-workaround
○ vscode-remote-workaround.service
     Loaded: loaded (/etc/systemd/user/vscode-remote-workaround.service; static)
     Active: inactive (dead)
TriggeredBy: ● vscode-remote-workaround.path
```

And then I run

```sh
❯ systemctl start --user vscode-remote-workaround
```

After this I was able to use vscode wsl properly, thanks a lot!
