### ISSUE TITLE
Unable to provide interactive input from shell

### ISSUE THREAD

**Issue by daspk04** [LGUG2Z/nixos-wsl-starter#13]
Hi @LGUG2Z ,

Thanks for this nice update. I just updated to the latest release. There seems to be some issue with the shell like I cannot enter `interactive input` from the shell. Currently I have a `flake.nix` which points to a private repo in GitLab and requires me to input `username` and `password` but I cannot enter anything in the shell. The shell just gets stuck on the below mentioned command:
```
Username for 'https://gitlab.com':
```

I didn't have this issue in the earlier version i.e. [nixos-wsl-starter(23.11)](https://github.com/LGUG2Z/nixos-wsl-starter/tree/18ce8e11bb0c462ffc813150a886647dbd7b46fa) which was based on `zsh` and `Lvim`.  So I tried to test by changing all the configuration for the shell back to `zsh` and `Lvim` and it seems to work as I can provide the `username` and `password`.

I might be missing some configuration for `fish` and `JeezyVim`. 

Any suggestion ?

Thanks

**Comment by LGUG2Z** [comment]
I would try setting the access token for Gitlab repos directly in your flake's `nix.settings` block:

Example from my own configuration where I set custom access tokens for private flakes on GitHub and GitLab:

```nix
{
  nix = {
    settings = {
      access-tokens = [
        "github.com=${secrets.github.personal_access_token}"
        "gitlab.com=OAuth2:${secrets.gitlab.personal_access_token}"
      ];
    };
  };
}
```

**Comment by daspk04** [comment]
> I would try setting the access token for Gitlab repos directly in your flake's `nix.settings` block:
> 
> Example from my own configuration where I set custom access tokens for private flakes on GitHub and GitLab:
> 
> ```nix
> {
>   nix = {
>     settings = {
>       access-tokens = [
>         "github.com=${secrets.github.personal_access_token}"
>         "gitlab.com=OAuth2:${secrets.gitlab.personal_access_token}"
>       ];
>     };
>   };
> }
> ```

Thanks @LGUG2Z for the suggestion! 

After some testing, I configured only `home.nix` file under the [`extraConfig`](https://github.com/LGUG2Z/nixos-wsl-starter/blob/91505977b9db2cd9af14d5c6597f7531eff628ff/home.nix#L146) for `git` and it worked. Actually at first I did also change the `nix.settings` but I wasn't sure how to add multiple accounts and tokens for `GitLab` under `nix.settings` so I commented it out and it seems like only configuration via git works.

Example configuration incase someone wants to configure multiple private account and token.

`extraConfig` for git in `home.nix`:

```
      extraConfig = {
        url = {
          "https://oauth2:${secrets.gitlab_token_abc}@gitlab.com/abc" = {
            insteadOf = "https://gitlab.com/abc";
          };
          "https://oauth2:${secrets.gitlab_token_xyz}@gitlab.com/xyz" = {
            insteadOf = "https://gitlab.com/xyz";
          };
        };
```

`Flake.nix` input url:
```
inputs {
    abc.url = "git+https://gitlab.com/abc/.../..";
    xyz.url = "git+https://gitlab.com/xyz/.../..";
}
```
