### ISSUE TITLE
Git not installed by default

### ISSUE THREAD

**Issue by jhirn** [LGUG2Z/nixos-wsl-starter#16]
Hey there.

I'm happy this repo exists and can jump start me into the world of Nix. I don't want to come off as a newb, but since this is a starter kit I felt I should raise an issue that git is not installed by default, only because the Readme jumps from `wsl -d NixOS` to `git clone`. I feel like instructions to install Git might be a bit more friendly. 

I was able to figure this out pretty quickly but it could be a bigger barrier for people new to Nix or Linux in general. As a Linux vet, I quickly found `nix-env -iA nixos.pkgs.gitAndTools.gitFull` got me onto the next step, but as a Nix newb I'm (over)thinking if this is valid in what's supposed to be a declarative approach to package management and configuration. As a neckbeard I'm wondering how to install emacs to edit `flake.nix` and feel like I made a mistake using `nix-env` when the next line says to "Install win32yank with scoop", which I had to learn is a Windows dependency I'm not familiar with (but I'm super excited to learn about because Chocolatly has never been a good experience). 

All depends on your target audience. Perhaps this is intended for people familiar with Nix to get started WSL in which case using scoop in windows and installing git is a no brainer. I could be totally off base in which case close and ignore this issue. I just feel the Readme may benefit from spelling out these steps (not the emacs install, that needs to be earned). I'm going to power through the install with some help from Claude or ChatGPT because i love the idea of a batteries included starter kit. 

Happy to provide more feedback or a PR for the Readme once I get through if welcomed.

**Comment by LGUG2Z** [comment]
Thanks for this feedback! It's been a while since I watched the walkthrough video linked in the README, but I think that I must have done these things that slipped through the cracks a little on the written walkthrough.

It would definitely be useful for others if you can take some time to watch through the walkthrough and make a PR with the missing "glue" steps that I have probably taken knowledge of for granted 🙏

**Comment by JumpIn-Git** [comment]
just add `nix-shell -p git` to the readme?

**Comment by LGUG2Z** [comment]
https://github.com/LGUG2Z/nixos-wsl-starter/blob/60974c6456bfd8d37fbe576517ddbb5f666bd8ba/home.nix#L19

`git` is in fact installed if you use recent versions of the starter `.tar.gz`
