### ISSUE TITLE
Fonts not correctly set

### ISSUE THREAD

**Issue by julian-hoch** [LGUG2Z/nixos-wsl-starter#2]
Hi,
I am quite new to NixOS, but I noticed that after following the instructions the fonts are not correctly set - the icons for example for folders and files when using ls are not displayed correctly (just squares). There might be a step I am missing?

**Comment by LGUG2Z** [comment]
Hi Julian!

Fonts which have compatibility with the various icons will need to be set on the terminal emulator you're using in Windows. For example, here is the font that I use in Windows Terminal which I believe supports all of the various icons shown by `lsd` and `starship`:

![image](https://github.com/LGUG2Z/nixos-wsl-starter/assets/13164844/8ee80532-8396-4149-813e-ae2a11523b4c)

**Comment by julian-hoch** [comment]
Thanks! That worked. I installed a font as indicated here: https://learn.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#install-a-nerd-font
After that, the icons show up correctly.
