### ISSUE TITLE
Error when rebuilding to new configuration

### ISSUE THREAD

**Issue by Astrotemporal** [LGUG2Z/nixos-wsl-starter#3]
Hello, after populating the username field and running `sudo nixos-rebuild switch --flake /tmp/configuration`, I get the following error message:

![image](https://github.com/LGUG2Z/nixos-wsl-starter/assets/69331365/11d98108-f2c0-45ca-afef-007ba0ff06c2)

**Comment by LGUG2Z** [comment]
Can you share an `ls -la` showing the permissions and owners of the config folder and any subfolders within it?

**Comment by Astrotemporal** [comment]
![image](https://github.com/LGUG2Z/nixos-wsl-starter/assets/69331365/40904943-c1d6-4daf-a5b2-a4796b1d3759)
Here's the `ls -la` for both `/tmp` and `/tmp/configurations`

**Comment by LGUG2Z** [comment]
Ah, apologies I wasn't clear, I meant the `~/.config` dir and  any subdirs under that. I have a feeling I know what the issue might be, I'm going to try and reproduce it but it would be good to have the data from you ^

**Comment by LGUG2Z** [comment]
I've just pushed a fix for this here, thanks for opening an issue and bringing this to my attention: https://github.com/LGUG2Z/nixos-wsl-starter/commit/01e2d20d7a815a97569eee28b5c777b06d5469ae

**Comment by Astrotemporal** [comment]
No problem, thanks for the speedy response!
