### ISSUE TITLE
git.sr.ht down

### ISSUE THREAD

**Issue by munkk01** [LGUG2Z/nixos-wsl-starter#4]
In case anyone is trying to follow this wonderful guide, during the initial rebuild process of switching to the flake.. It makes calls to `https://git.sr.ht` which are currently failing.

This is due to the service being down temporarily due to a DDoS attack against SourceHut.

I thought it was a `me` issue until researching into potential causes of the problem.

This is *NOT* due to anything directly related to this repo and its code. I'm supplying this as an FYI in case someone somehow ends up in the situation I was in a few moments ago. Figured I'd share!

### Reference:
https://status.sr.ht/

**Comment by LGUG2Z** [comment]
I'm not sure if any of inputs in `flake.nix` are referring to SourceHut in their dependency trees, but if they are not, you may be able to get around this for now by commenting out all of the packages here (https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/home.nix#L10) and here (https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/home.nix#L39) and then gradually adding them back in with subsequent rebuilds until you are able to isolate the ones that are dependent on SourceHut repos and leave those commented until it's back online 🤞

**Comment by munkk01** [comment]
> I'm not sure if any of inputs in `flake.nix` are referring to SourceHut in their dependency trees, but if they are not, you may be able to get around this for now by commenting out all of the packages here (https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/home.nix#L10) and here (https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/home.nix#L39) and then gradually adding them back in with subsequent rebuilds until you are able to isolate the ones that are dependent on SourceHut repos and leave those commented until it's back online 🤞

That will be the tricky part as the only output from the build is:
```
[1 built, 6 copied (172.3 MiB), 95.9 MiB DL] downloading 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz'
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz': Timeout was reached (28); retrying in 254 ms
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz': Timeout was reached (28); retrying in 666 ms
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz': Timeout was reached (28); retrying in 1315 ms
```

Seems trivial to isolate which package(s) are requiring the call to that one. I got busy with work and haven't had time to get back to it.. But I should here momentarily.

**Comment by munkk01** [comment]
Closing issue. SourceHut is back online. WSL rebuild functioned normally.
